version: '3'

services:  
  posts_collector:
    build: collectors/twitter_posts
    volumes:
      #Worker
      - ./collectors/twitter_posts:/collectors/twitter_posts
    working_dir: /collectors/twitter_posts/src
    command: main.py  
    links:
      - mongo
    depends_on:
      - mongo     

  people_collector:
    build: collectors/twitter_people
    volumes:
      #Worker
      - ./collectors/twitter_people:/collectors/twitter_people
    working_dir: /collectors/twitter_people/src
    command: main.py  
    links:
      - mongo
    depends_on:
      - mongo      

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    #environment:
      #MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: example
      #MONGO_DATA_DIR: /data/db
      #MONGO_LOG_DIR: /dev/null
    volumes:
      - './data:/data/db'
      

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      
