version: '3'

services:  
  posts_collector:
    build: collectors/tweepy_collector
    volumes:
      #Worker
      - ./collectors/tweepy_collector:/collectors/tweepy_collector
    working_dir: /collectors/tweepy_collector/src
    command: posts_collector.py /collectors/tweepy_collector/config/config.json posts_data --env LOCAL
    links:
      - mongo
    depends_on:
      - mongo       

  people_collector:
    build: collectors/tweepy_collector
    volumes:
      #Worker
      - ./collectors/tweepy_collector:/collectors/tweepy_collector
    working_dir: /collectors/tweepy_collector/src
    command: people_collector.py /collectors/tweepy_collector/config/config.json people_data --env LOCAL
    links:
      - mongo
    depends_on:
      - mongo      

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017    
    volumes:
      - './data:/data/db'      